# Generated by Django 5.1.3 on 2024-11-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_event_date'),
        ('portal', '0007_profiletype'),
    ]

    operations = [
    ]
